{{- if .Values.config.secretEnv.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "palworld.secret.name" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.config.secretEnv.env }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}