apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
    {{- if and .Values.rcon.enabled .Values.rcon.expose }}
    - port: {{ .Values.rcon.port }}
      targetPort: rcon
      protocol: TCP
      name: rcon
    {{- end }}
  selector:
    {{- include "palworld.selectorLabels" . | nindent 4 }}
